# Generated by Django 4.2.1 on 2023-08-03 15:22

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskController',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_and_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('state_task', models.CharField(choices=[('INICIADO', 'iniciado'), ('COMPLETADO', 'completado')], default='INICIADO', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
