version: '3.9'

services:
  db_postgres:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: postgres:13.11
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}


  web:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db_postgres


volumes:
  database: