version: '3.9'

services:
  db_postgres:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: postgres:13.11
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - '543:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}


  web:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    container_name: django
    volumes:
      - .:/app
    ports:
      - '8001:8001'
    depends_on:
      - db_postgres

  redis:
    image: redis:6.0


volumes:
  database: