version: '3.9'

services:

  web:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    container_name: django
    volumes:
      - .:/app
    ports:
      - '8001:8001'

  redis:
    image: redis:6.0
    container_name: redis_docker
    ports:
      - '6379:6379'


volumes:
  database:
