# Generated by Django 4.2.1 on 2023-05-12 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=300)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned', to=settings.AUTH_USER_MODEL)),
                ('task_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_Creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Task',
            },
        ),
    ]
