# Generated by Django 4.2.1 on 2023-07-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('BASICO', 'basico'), ('VENDEDOR', 'vendedor'), ('COMPRADOR', 'comprador')], default='BASICO', max_length=100, verbose_name='rol'),
        ),
    ]
