# Generated by Django 4.2.1 on 2023-07-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendbooks',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
