# Generated by Django 4.2.1 on 2023-07-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_lendbooks_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lendbooks',
            name='is_free',
        ),
        migrations.AddField(
            model_name='books',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
